rigid_bodies:
    "Rigid1":
        pose: Rigid1/pose
        pose2d: Rigid1/ground_pose
        odom: Rigid1/Odom
        child_frame_id: rigid1_frame
        parent_frame_id: optitrack_world

optitrack_config:
    multicast_address: 224.0.0.1
    command_port: 1510
    data_port: 9000
    enable_optitrack: true
